(function initLanguageProvider(global) {
  const SUPPORTED_CODES = [
    "ENG", "FRE", "GER", "JPN", "KOR", "CHS", "CHT", "SPA",
    "POR", "HIN", "RUS", "TUR", "VIE", "THA", "IND"
  ];

  const DISPLAY_NAMES = {
    ENG: "English",
    FRE: "français",
    GER: "Deutsch",
    JPN: "日本語",
    KOR: "한국어",
    CHS: "简体中文",
    CHT: "繁體中文",
    SPA: "español",
    POR: "português",
    HIN: "हिन्दी",
    RUS: "Русский",
    TUR: "Türkçe",
    VIE: "Tiếng Việt",
    THA: "ไทย",
    IND: "Bahasa Indonesia"
  };

  const TRANSLATIONS = {
    ENG: {
      "settings.title": "Settings",
      "settings.back": "Back",
      "settings.theme": "Theme",
      "settings.theme.system": "System",
      "settings.theme.dark": "Dark",
      "settings.theme.light": "Light",
      "settings.language": "Language",
      "settings.applySaved": "Saved.",
      "settings.cancel": "Cancel",
      "settings.save": "Save",
      "settings.apply": "Apply",
      "settings.delete": "Delete",
      "settings.name": "Name",
      "settings.url": "URL",
      "settings.email": "Email",
      "settings.password": "Password",
      "settings.logoUrl": "Logo image URL",
      "settings.backgroundUrl": "Background image URL",
      "settings.iconImageUrl": "Icon image URL",
      "settings.iconColor": "Icon color",
      "settings.uploadHint100kb": "Image upload: up to 100KB",
      "settings.account": "Account / Auth",
      "settings.logout": "Logout",
      "settings.loginEmail": "Login with Email",
      "settings.googleLogin": "Sign in with Google",
      "settings.noAccount": "No account yet? Go to email sign up",
      "settings.upgrade": "Upgrade Account",
      "settings.profileImageUrl": "Profile image URL",
      "settings.displayName": "Display name",
      "settings.org": "Organization",
      "settings.workspaceOrder": "Workspaces (drag to reorder)",
      "settings.joinCode": "Organization invite code",
      "settings.join": "Join",
      "settings.bulkConfig": "Bulk config for current page",
      "settings.bulkCopy": "Copy exported config",
      "settings.bulkHint": "Paste config code to apply page settings at once.",
      "settings.privacy": "Make my page private (hide from org members)",
      "settings.inviteCodeGen": "Generate invite code (24 hours)",
      "settings.copyInviteUrl": "Copy invite URL",
      "settings.orgName": "Organization name",
      "settings.orgIconUrl": "Organization icon URL",
      "settings.inviteEmail": "Invite recipient email",
      "settings.inviteSend": "Send invite",
      "settings.inviteHint": "Opens your default mail app with the invite link prefilled.",
      "settings.dockModeMembers": "Show team members in Dock",
      "settings.dockModeSpaces": "Show spaces in Dock",
      "settings.dockAddHide": "Hide add button in Dock",
      "settings.dockAddShow": "Show add button in Dock",
      "settings.userNamePlaceholder": "e.g. Alex",
      "settings.shortcutNamePlaceholder": "e.g. ChatGPT",
      "settings.shortcutUrlPlaceholder": "example.com or https://…",
      "settings.signupHandlePlaceholder": "e.g. coolhandle42",
      "settings.signupPasswordPlaceholder": "At least 6 characters",
      "settings.signupPasswordConfirmPlaceholder": "Re-enter password",
      "settings.orgNamePlaceholder": "Organization name",
      "settings.userDockAria": "User dock",
      "settings.addUserModalTitle": "Add User",
      "settings.shortcutModalTitle": "Add Shortcut",
      "settings.shortcutEditModalTitle": "Edit Shortcut",
      "settings.policyDoc": "Policy document",
      "settings.loading": "Loading...",
      "settings.policyLoadFailed": "Failed to load document. Check network or CORS settings.",
      "settings.privacyPolicyTitle": "Privacy Policy",
      "settings.termsTitle": "Terms of Service",
      "settings.orgStatusPersonal": "Current: Personal mode (organizations: {count})",
      "settings.orgStatusOwner": "Current organization: {name} (Owner)",
      "settings.orgStatusMember": "Current organization: {name} (Member)",
      "settings.addLabel": "Add",
      "settings.edit": "Edit",
      "settings.prevPage": "Previous page",
      "settings.nextPage": "Next page",
      "settings.pageN": "Page {n}",
      "settings.noEditPermission": "You do not have edit permission for this page.",
      "settings.urlRequired": "Please enter a URL.",
      "settings.maxShortcuts": "You can save up to {cap} shortcuts. (Max {cells} cells per page, max {pages} data pages)",
      "settings.more": "More",
      "settings.spaceSettings": "Space settings",
      "settings.startHomeShort": "Start/Home",
      "settings.aliasSet": "Set alias",
      "settings.invite": "Invite",
      "settings.personal": "Personal",
      "settings.loginEmailHint": "Login email: {email}",
      "settings.copyDone": "Copied!",
      "settings.nameRequired": "Please enter a name.",
      "settings.profileSaveFailed": "Failed to save profile: {error}",
      "settings.orgNameRequired": "Please enter organization name.",
      "settings.saveFailed": "Save failed: {error}",
      "settings.spaceSaved": "Space settings have been saved.",
      "settings.nameSaveFailed": "Failed to save name: {error}",
      "settings.nameSaved": "Name has been saved.",
      "settings.ownerOnlyManageMembers": "Only owners can manage members.",
      "settings.userEditModalTitle": "Edit User",
      "settings.aliasModalTitle": "Set Alias",
      "settings.aliasLabel": "Alias",
      "settings.memberPagePrivate": "This member's page is private.",
      "settings.themeSaveFailed": "Failed to save theme: {error}",
      "settings.languageSaveFailed": "Failed to save language: {error}",
      "settings.orgLoadFailed": "Failed to load organization list",
      "settings.rankingColumnMissing": "ranking column is missing",
      "settings.applySchemaThenRetry": "Apply supabase/shortcut_schema.sql and try again.",
      "settings.shortcutDataLoadFailed": "Failed to load shortcuts data",
      "settings.preSaveFetchFailed": "Failed to fetch before save",
      "settings.shortcutUpdateFailed": "Failed to update shortcut",
      "settings.shortcutSaveFailed": "Failed to save shortcut",
      "settings.handleChecking": "Checking handle...",
      "settings.handleAvailable": "Handle is available.",
      "settings.handleTaken": "Handle is already taken.",
      "settings.userNameLabel": "Name",
      "settings.onlyOrgMembersCanAlias": "Only organization members can set alias.",
      "settings.ownerOnlyInviteCode": "Only owners can generate invite code.",
      "settings.inviteCodeCreateFailed": "Failed to create invite code.",
      "settings.inviteCodeCreated": "Invite code created: {code}",
      "settings.inviteCodeExpired": "Invite code has expired.",
      "settings.inviteInfoNotFound": "Invite information not found.",
      "settings.inviteAcceptFailed": "Failed to accept invite. Check invite update policy.",
      "settings.transferOwner": "Transfer organization ownership",
      "settings.transferOwnerBtn": "Transfer ownership",
      "settings.transferOwnerHint": "Once transferred, it cannot be undone. You can leave the organization afterwards.",
      "settings.deleteOrg": "Delete organization",
      "settings.deleteOrgBtn": "Delete organization",
      "settings.deleteOrgHint": "To delete, type <code>Delete</code> in the confirmation popup. This action cannot be undone.",
      "settings.selectNewOwner": "Select a new owner",
      "settings.noTransferCandidate": "No member available for transfer",
      "settings.ownerTransferOnly": "Only owners can transfer ownership.",
      "settings.selectNewOwnerRequired": "Please select a new owner.",
      "settings.ownerTransferFailed": "Failed to transfer ownership.",
      "settings.ownerTransferred": "Ownership has been transferred.",
      "settings.ownerDeleteOnly": "Only owners can delete this organization.",
      "settings.orgDeleteFailed": "Failed to delete organization.",
      "settings.orgDeleteConfirmTitle": "Confirm organization deletion",
      "settings.orgDeleteConfirmBody": "This action cannot be undone. To continue, type <b>Delete</b>.",
      "settings.confirm": "Confirm",
      "settings.leaveOrg": "Leave organization",
      "settings.leaveOrgConfirm": "Are you sure you want to leave this organization?",
      "settings.leaveOrgConfirmWithName": "Are you sure you want to leave {name}?",
      "settings.ownerMustTransferBeforeLeave": "Owners must transfer ownership before leaving.",
      "settings.orgLeaveFailed": "Failed to leave organization.",
      "settings.orgLeft": "You have left the organization.",
      "settings.orgJoinDone": "Organization join complete",
      "settings.sessionRestoreFailed": "Session restore failed",
      "settings.supabaseConfigMissing": "Supabase connection config is empty. Check hardcoded config values in the code.",
      "settings.loginDone": "Logged in.",
      "settings.emailPasswordRequired": "Please enter email/password.",
      "settings.loginFailed": "Login failed",
      "settings.loginException": "Exception while processing login",
      "settings.signupPasswordMismatch": "Passwords do not match.",
      "settings.signupHandleRequired": "Please enter a handle.",
      "settings.signupHandleTakenLong": "This handle is already in use. Please choose another.",
      "settings.signupFailed": "Sign-up failed",
      "settings.signupFailedSimple": "Failed to sign up.",
      "settings.signupRequestedVerifyEmail": "Sign-up request received. Please verify your email, then sign in.",
      "settings.profileCreateFailed": "Failed to create profile",
      "settings.profileCreatePartial": "Account was created but failed to save profile: {error}",
      "settings.signupDone": "Sign-up complete.",
      "settings.signupDoneCheckEmail": "Signed up. Please check your email before signing in.",
      "settings.signupException": "Exception while processing sign-up",
      "settings.processingError": "An error occurred while processing.",
      "settings.logoutFailed": "Logout failed",
      "settings.logoutWarning": "Warning while processing logout",
      "settings.logoutErrorLocalCleared": "{error} (local state cleared)",
      "settings.loggedOut": "Logged out.",
      "settings.orgCreateFailed": "Failed to create organization: {error}",
      "settings.invitePanelOrgOnly": "Invite panel can only be opened in organization mode.",
      "settings.generateInviteCodeFirst": "Generate an invite code first.",
      "settings.inviteUrlCopied": "Invite URL copied.",
      "settings.emailRequired": "Please enter email.",
      "settings.enterJoinCode": "Please enter join code.",
      "settings.onlySelfAliasEdit": "Only your own alias can be edited.",
      "settings.dbFunctionMissing": "DB function is missing. Please apply supabase/shortcut_schema.sql.",
      "settings.aliasEditNoPermission": "No permission to edit alias.",
      "settings.aliasSaveFailed": "Failed to save alias: {error}",
      "settings.aliasSaved": "Alias saved.",
      "settings.onlySelfProfileEdit": "Only your own profile can be edited.",
      "settings.profileSaveFailedSimple": "Failed to save profile: {error}",
      "settings.orgIconSizeLimit": "Organization icon image must be 100KB or less.",
      "settings.profileImageSizeLimit": "Profile image must be 100KB or less.",
      "settings.backgroundImageSizeLimit": "Background image must be 100KB or less.",
      "settings.noLogoEditPermission": "You do not have permission to edit the current logo.",
      "settings.logoImageSizeLimit": "Logo image must be 100KB or less.",
      "settings.authEventFailed": "Auth event handling failed",
      "settings.joinOrgQuestion": "Join {name}?",
      "settings.googleScriptLoadFailed": "Failed to load Google login script.",
      "settings.googleCredentialMissing": "Did not receive login credentials from Google.",
      "settings.inviteMailSubject": "{name} space invitation",
      "settings.inviteMailBody": "Hello,\n\nYou can accept the {name} space invitation from the link below.\n\n{url}\n",
      "settings.defaultAppTitle": "Quick links for web pages",
      "settings.errorPrefix": "[Error] {message}",
      "settings.markedLoadFailed": "Failed to load marked.",
      "settings.planCurrent": "Current plan",
      "settings.planIncluded": "Included",
      "settings.planUpgrade": "Upgrade",
      "settings.planStartTeam": "Start team",
      "settings.needLogin": "Login is required.",
      "settings.noSession": "No session found. Please sign in again.",
      "settings.noApiBase": "Unable to determine API base URL.",
      "settings.checkoutCreateFailed": "Failed to create checkout.",
      "settings.checkoutNoUrl": "Did not receive checkout URL.",
      "settings.polarPortalMissing": "Polar customer portal URL is missing. Set meta polar-portal-url or window.PRISM_TAB_POLAR.customerPortalUrl.",
      "settings.userAdd": "Add User",
      "settings.userEdit": "Edit User",
      "settings.shortcutAdd": "Add Shortcut",
      "settings.shortcutEdit": "Edit Shortcut",
      "settings.userAddBtnTitle": "Add user",
      "settings.userDockLabel": "User dock",
      "settings.startAndHomeTitle": "Set as Start & Home",
      "settings.startAndHomeDesc": "Set personal space as the first page on a new tab.",
      "settings.startAndHomeBtn": "Set as Start & Home",
      "settings.startAndHomeToast": "Set as Start & Home.",
      "banner.startAndHome": "Set as Start & Home and move faster",
      "banner.startAndHomeBtn": "Set as Start & Home",
      "signup.title": "Sign up",
      "signup.username": "Username",
      "signup.handle": "Handle (@)",
      "signup.email": "Email",
      "signup.password": "Password",
      "signup.passwordConfirm": "Confirm password",
      "signup.birthdate": "Birthdate",
      "signup.gender": "Gender",
      "signup.gender.none": "Prefer not to select",
      "signup.gender.male": "Male",
      "signup.gender.female": "Female",
      "signup.gender.other": "Other",
      "signup.gender.noanswer": "Prefer not to answer",
      "signup.submit": "Sign up"
    },
    KOR: {
      "settings.title": "설정",
      "settings.back": "뒤로",
      "settings.theme": "테마",
      "settings.theme.system": "시스템",
      "settings.theme.dark": "다크",
      "settings.theme.light": "화이트",
      "settings.language": "언어",
      "settings.applySaved": "저장했습니다.",
      "settings.cancel": "취소",
      "settings.save": "저장",
      "settings.apply": "적용",
      "settings.delete": "삭제",
      "settings.name": "이름",
      "settings.url": "URL",
      "settings.email": "이메일",
      "settings.password": "비밀번호",
      "settings.logoUrl": "로고 이미지 URL",
      "settings.backgroundUrl": "배경화면 URL",
      "settings.iconImageUrl": "아이콘 이미지 URL",
      "settings.iconColor": "아이콘 색상",
      "settings.uploadHint100kb": "이미지 업로드: 100KB 이하",
      "settings.account": "계정 / 인증",
      "settings.logout": "로그아웃",
      "settings.loginEmail": "이메일로 로그인",
      "settings.googleLogin": "Google 로그인",
      "settings.noAccount": "계정이 없으신가요? 이메일로 회원가입 하러가기",
      "settings.upgrade": "계정 업그레이드",
      "settings.profileImageUrl": "프로필 이미지 URL",
      "settings.displayName": "표시 이름",
      "settings.org": "조직",
      "settings.workspaceOrder": "작업 영역 (드래그로 우선순위 변경)",
      "settings.joinCode": "조직 가입 코드",
      "settings.join": "가입",
      "settings.bulkConfig": "현재 페이지 일괄 설정 코드",
      "settings.bulkCopy": "일괄 추출 복사",
      "settings.bulkHint": "코드를 붙여넣어 페이지 설정을 한 번에 적용합니다.",
      "settings.privacy": "내 페이지 비공개 (조직 구성원에게 숨김)",
      "settings.inviteCodeGen": "초대 코드 생성(24시간)",
      "settings.copyInviteUrl": "초대 URL 복사",
      "settings.orgName": "조직 이름",
      "settings.orgIconUrl": "조직 아이콘 URL",
      "settings.inviteEmail": "초대 받을 이메일",
      "settings.inviteSend": "초대 보내기",
      "settings.inviteHint": "기본 메일 앱으로 초대 링크가 담긴 메일 작성 화면이 열립니다.",
      "settings.dockModeMembers": "Dock에 팀 멤버 표시",
      "settings.dockModeSpaces": "Dock에 스페이스 표시",
      "settings.dockAddHide": "Dock에 추가 숨기기",
      "settings.dockAddShow": "Dock에 추가 표시",
      "settings.userNamePlaceholder": "예: Alex",
      "settings.shortcutNamePlaceholder": "예: ChatGPT",
      "settings.shortcutUrlPlaceholder": "example.com 또는 https://…",
      "settings.signupHandlePlaceholder": "예: coolhandle42",
      "settings.signupPasswordPlaceholder": "6자 이상",
      "settings.signupPasswordConfirmPlaceholder": "비밀번호 재입력",
      "settings.orgNamePlaceholder": "조직 이름",
      "settings.userDockAria": "유저 독",
      "settings.addUserModalTitle": "유저 추가",
      "settings.shortcutModalTitle": "바로가기 추가",
      "settings.shortcutEditModalTitle": "바로가기 수정",
      "settings.policyDoc": "정책 문서",
      "settings.loading": "불러오는 중...",
      "settings.policyLoadFailed": "문서를 불러오지 못했습니다. 네트워크 또는 CORS 설정을 확인해 주세요.",
      "settings.privacyPolicyTitle": "개인정보 처리방침",
      "settings.termsTitle": "이용약관",
      "settings.orgStatusPersonal": "현재: 개인 모드 (조직 {count}개)",
      "settings.orgStatusOwner": "현재 조직: {name} (Owner)",
      "settings.orgStatusMember": "현재 조직: {name} (Member)",
      "settings.addLabel": "추가",
      "settings.edit": "편집",
      "settings.prevPage": "이전 페이지",
      "settings.nextPage": "다음 페이지",
      "settings.pageN": "페이지 {n}",
      "settings.noEditPermission": "현재 페이지는 편집 권한이 없습니다.",
      "settings.urlRequired": "URL을 입력해 주세요.",
      "settings.maxShortcuts": "바로가기는 최대 {cap}개까지 저장할 수 있습니다. (페이지당 최대 {cells}칸·데이터 페이지 최대 {pages}장)",
      "settings.more": "더보기",
      "settings.spaceSettings": "스페이스 설정",
      "settings.startHomeShort": "시작/홈페이지",
      "settings.aliasSet": "별명 설정하기",
      "settings.invite": "초대하기",
      "settings.personal": "개인",
      "settings.loginEmailHint": "로그인 이메일: {email}",
      "settings.copyDone": "복사됨!",
      "settings.nameRequired": "이름을 입력하세요.",
      "settings.profileSaveFailed": "프로필 저장 실패: {error}",
      "settings.orgNameRequired": "조직 이름을 입력하세요.",
      "settings.saveFailed": "저장 실패: {error}",
      "settings.spaceSaved": "스페이스 설정이 저장되었습니다.",
      "settings.nameSaveFailed": "이름 저장 실패: {error}",
      "settings.nameSaved": "이름이 저장되었습니다.",
      "settings.ownerOnlyManageMembers": "Owner만 구성원을 관리할 수 있습니다.",
      "settings.userEditModalTitle": "유저 수정",
      "settings.aliasModalTitle": "별명 설정",
      "settings.aliasLabel": "별명 설정",
      "settings.memberPagePrivate": "이 구성원의 페이지는 비공개입니다.",
      "settings.themeSaveFailed": "테마 저장 실패: {error}",
      "settings.languageSaveFailed": "언어 저장 실패: {error}",
      "settings.orgLoadFailed": "조직 목록 로딩 실패",
      "settings.rankingColumnMissing": "ranking 컬럼이 없습니다",
      "settings.applySchemaThenRetry": "supabase/shortcut_schema.sql 적용 후 다시 시도하세요.",
      "settings.shortcutDataLoadFailed": "바로가기 데이터 로딩 실패",
      "settings.preSaveFetchFailed": "저장 전 조회 실패",
      "settings.shortcutUpdateFailed": "바로가기 업데이트 실패",
      "settings.shortcutSaveFailed": "바로가기 저장 실패",
      "settings.handleChecking": "핸들 확인 중...",
      "settings.handleAvailable": "사용 가능한 핸들입니다.",
      "settings.handleTaken": "이미 사용 중인 핸들입니다.",
      "settings.userNameLabel": "이름",
      "settings.onlyOrgMembersCanAlias": "조직 구성원만 별명을 설정할 수 있습니다.",
      "settings.ownerOnlyInviteCode": "Owner만 초대 코드를 생성할 수 있습니다.",
      "settings.inviteCodeCreateFailed": "초대 코드 생성에 실패했습니다.",
      "settings.inviteCodeCreated": "초대 코드 생성 완료: {code}",
      "settings.inviteCodeExpired": "초대 코드가 만료되었습니다.",
      "settings.inviteInfoNotFound": "초대 정보를 찾을 수 없습니다.",
      "settings.inviteAcceptFailed": "초대 수락 처리에 실패했습니다. 초대 업데이트 정책을 확인해 주세요.",
      "settings.transferOwner": "조직 Owner 권한 넘기기",
      "settings.transferOwnerBtn": "권한 넘기기",
      "settings.transferOwnerHint": "권한을 넘기면 되돌릴 수 없습니다. 이후에는 조직을 떠날 수 있습니다.",
      "settings.deleteOrg": "조직 삭제",
      "settings.deleteOrgBtn": "조직 삭제",
      "settings.deleteOrgHint": "삭제하려면 확인 팝업에서 <code>Delete</code>를 입력해야 하며, 이 작업은 번복할 수 없습니다.",
      "settings.selectNewOwner": "새 Owner를 선택하세요",
      "settings.noTransferCandidate": "넘길 수 있는 멤버가 없습니다",
      "settings.ownerTransferOnly": "Owner만 권한을 넘길 수 있습니다.",
      "settings.selectNewOwnerRequired": "새 Owner를 선택해 주세요.",
      "settings.ownerTransferFailed": "Owner 권한 넘기기에 실패했습니다.",
      "settings.ownerTransferred": "Owner 권한을 넘겼습니다.",
      "settings.ownerDeleteOnly": "Owner만 조직을 삭제할 수 있습니다.",
      "settings.orgDeleteFailed": "조직 삭제에 실패했습니다.",
      "settings.orgDeleteConfirmTitle": "조직 삭제 확인",
      "settings.orgDeleteConfirmBody": "이 작업은 번복할 수 없습니다. 계속하려면 <b>Delete</b>를 입력하세요.",
      "settings.confirm": "확인",
      "settings.leaveOrg": "조직 떠나기",
      "settings.leaveOrgConfirm": "정말 이 조직을 떠나시겠습니까?",
      "settings.leaveOrgConfirmWithName": "{name} 조직을 정말 떠나시겠습니까?",
      "settings.ownerMustTransferBeforeLeave": "Owner는 떠나기 전에 다른 Owner를 지정해야 합니다.",
      "settings.orgLeaveFailed": "조직 떠나기에 실패했습니다.",
      "settings.orgLeft": "조직을 떠났습니다.",
      "settings.orgJoinDone": "조직 가입 완료",
      "settings.sessionRestoreFailed": "세션 복원 실패",
      "settings.supabaseConfigMissing": "Supabase 연결 설정이 비어있습니다. 코드의 고정 설정값을 확인하세요.",
      "settings.loginDone": "로그인되었습니다.",
      "settings.emailPasswordRequired": "이메일/비밀번호를 입력하세요.",
      "settings.loginFailed": "로그인 실패",
      "settings.loginException": "로그인 처리 중 예외",
      "settings.signupPasswordMismatch": "비밀번호가 일치하지 않습니다.",
      "settings.signupHandleRequired": "핸들을 입력하세요.",
      "settings.signupHandleTakenLong": "이미 사용 중인 핸들입니다. 다른 핸들을 선택해 주세요.",
      "settings.signupFailed": "회원가입 실패",
      "settings.signupFailedSimple": "가입에 실패했습니다.",
      "settings.signupRequestedVerifyEmail": "가입 요청을 접수했습니다. 이메일 인증 후 로그인해 주세요.",
      "settings.profileCreateFailed": "프로필 생성 실패",
      "settings.profileCreatePartial": "계정은 생성되었으나 프로필 저장에 실패했습니다: {error}",
      "settings.signupDone": "회원가입이 완료되었습니다.",
      "settings.signupDoneCheckEmail": "가입했습니다. 이메일을 확인한 뒤 로그인해 주세요.",
      "settings.signupException": "회원가입 처리 중 예외",
      "settings.processingError": "처리 중 오류가 났습니다.",
      "settings.logoutFailed": "로그아웃 실패",
      "settings.logoutWarning": "로그아웃 처리 중 경고",
      "settings.logoutErrorLocalCleared": "{error} (로컬 상태는 정리됨)",
      "settings.loggedOut": "로그아웃되었습니다.",
      "settings.orgCreateFailed": "조직 생성 실패: {error}",
      "settings.invitePanelOrgOnly": "조직 모드에서만 초대 패널을 열 수 있습니다.",
      "settings.generateInviteCodeFirst": "먼저 초대 코드를 생성하세요.",
      "settings.inviteUrlCopied": "초대 URL 복사 완료",
      "settings.emailRequired": "이메일을 입력하세요.",
      "settings.enterJoinCode": "가입 코드를 입력하세요.",
      "settings.onlySelfAliasEdit": "본인 별명만 수정할 수 있습니다.",
      "settings.dbFunctionMissing": "DB 함수가 없습니다. supabase/shortcut_schema.sql을 적용해주세요.",
      "settings.aliasEditNoPermission": "별명 수정 권한이 없습니다.",
      "settings.aliasSaveFailed": "별명 저장 실패: {error}",
      "settings.aliasSaved": "별명이 저장되었습니다.",
      "settings.onlySelfProfileEdit": "본인 프로필만 수정할 수 있습니다.",
      "settings.profileSaveFailedSimple": "프로필 저장 실패: {error}",
      "settings.orgIconSizeLimit": "조직 아이콘 이미지는 100KB 이하만 가능합니다.",
      "settings.profileImageSizeLimit": "프로필 이미지는 100KB 이하만 가능합니다.",
      "settings.backgroundImageSizeLimit": "배경 이미지는 100KB 이하만 가능합니다.",
      "settings.noLogoEditPermission": "현재 로고 편집 권한이 없습니다.",
      "settings.logoImageSizeLimit": "로고 이미지는 100KB 이하만 가능합니다.",
      "settings.authEventFailed": "Auth 이벤트 처리 실패",
      "settings.joinOrgQuestion": "{name}에 가입할까요?",
      "settings.googleScriptLoadFailed": "Google 로그인 스크립트를 불러오지 못했습니다.",
      "settings.googleCredentialMissing": "Google에서 로그인 정보를 받지 못했습니다.",
      "settings.inviteMailSubject": "{name} 스페이스 초대",
      "settings.inviteMailBody": "안녕하세요,\n\n아래 링크에서 {name} 스페이스 초대를 수락할 수 있습니다.\n\n{url}\n",
      "settings.defaultAppTitle": "웹페이지 z 바로가기",
      "settings.errorPrefix": "[오류] {message}",
      "settings.markedLoadFailed": "marked 로드 실패",
      "settings.planCurrent": "현재 플랜",
      "settings.planIncluded": "포함됨",
      "settings.planUpgrade": "업그레이드",
      "settings.planStartTeam": "팀으로 시작",
      "settings.needLogin": "로그인이 필요합니다.",
      "settings.noSession": "세션이 없습니다. 다시 로그인해 주세요.",
      "settings.noApiBase": "API 베이스 URL을 확인할 수 없습니다.",
      "settings.checkoutCreateFailed": "체크아웃 생성에 실패했습니다.",
      "settings.checkoutNoUrl": "체크아웃 URL을 받지 못했습니다.",
      "settings.polarPortalMissing": "Polar 고객 포털 링크가 없습니다. meta polar-portal-url 또는 window.PRISM_TAB_POLAR.customerPortalUrl 을 설정해 주세요.",
      "settings.userAdd": "유저 추가",
      "settings.userEdit": "유저 수정",
      "settings.shortcutAdd": "바로가기 추가",
      "settings.shortcutEdit": "바로가기 수정",
      "settings.userAddBtnTitle": "유저 추가",
      "settings.userDockLabel": "유저 독",
      "settings.startAndHomeTitle": "시작 및 홈페이지로 설정하기",
      "settings.startAndHomeDesc": "개인 스페이스를 새 탭에서 가장 먼저 열리도록 지정합니다.",
      "settings.startAndHomeBtn": "시작 및 홈페이지로 설정",
      "settings.startAndHomeToast": "시작 및 홈페이지로 설정했습니다.",
      "banner.startAndHome": "시작 및 홈페이지로 설정하고 더 빠르게 움직이세요",
      "banner.startAndHomeBtn": "시작 및 홈페이지로 설정",
      "signup.title": "회원가입",
      "signup.username": "사용자 이름",
      "signup.handle": "핸들 (@)",
      "signup.email": "이메일 주소",
      "signup.password": "비밀번호",
      "signup.passwordConfirm": "비밀번호 확인",
      "signup.birthdate": "생년월일",
      "signup.gender": "성별",
      "signup.gender.none": "선택 안 함",
      "signup.gender.male": "남성",
      "signup.gender.female": "여성",
      "signup.gender.other": "기타",
      "signup.gender.noanswer": "응답하지 않음",
      "signup.submit": "가입하기"
    }
  };

  function normalizeLanguageCode(value) {
    const raw = String(value || "").trim().toUpperCase();
    if (!raw) return "ENG";
    if (SUPPORTED_CODES.includes(raw)) return raw;

    const lower = String(value || "").trim().toLowerCase();
    if (lower.startsWith("ko")) return "KOR";
    if (lower.startsWith("en")) return "ENG";
    if (lower.startsWith("fr")) return "FRE";
    if (lower.startsWith("de")) return "GER";
    if (lower.startsWith("ja")) return "JPN";
    if (lower.startsWith("zh-hant") || lower.startsWith("zh-tw") || lower.startsWith("zh-hk")) return "CHT";
    if (lower.startsWith("zh")) return "CHS";
    if (lower.startsWith("es")) return "SPA";
    if (lower.startsWith("pt")) return "POR";
    if (lower.startsWith("hi")) return "HIN";
    if (lower.startsWith("ru")) return "RUS";
    if (lower.startsWith("tr")) return "TUR";
    if (lower.startsWith("vi")) return "VIE";
    if (lower.startsWith("th")) return "THA";
    if (lower.startsWith("id")) return "IND";
    return "ENG";
  }

  function detectSystemLanguageCode() {
    const nav = global.navigator || {};
    return normalizeLanguageCode(nav.language || nav.userLanguage || "en");
  }

  function t(langCode, key, fallback) {
    const lang = normalizeLanguageCode(langCode);
    const selected = TRANSLATIONS[lang] || TRANSLATIONS.ENG;
    if (Object.prototype.hasOwnProperty.call(selected, key)) return selected[key];
    if (Object.prototype.hasOwnProperty.call(TRANSLATIONS.ENG, key)) return TRANSLATIONS.ENG[key];
    return fallback || key;
  }

  function getLanguageOptions(displayLangCode) {
    return SUPPORTED_CODES.map((code) => ({
      code,
      label: DISPLAY_NAMES[code] || code
    }));
  }

  global.LanguageProvider = {
    SUPPORTED_CODES,
    TRANSLATIONS,
    normalizeLanguageCode,
    detectSystemLanguageCode,
    t,
    getLanguageOptions
  };
})(window);
